- .gitignore
- app/src/main/java/edu/uw/tcss450/chatapp/MainActivity.java
What does this implement/fix? Explain your changes.
---------------------------------------------------
Added an unused file to the .gitignore and added a sample comment
Does this close any currently open issues?
------------------------------------------
No
Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
No
Any other comments?
-------------------
No
Where has this been tested?
---------------------------
**Operating System:** …
**Platform:** …
**Target Platform:** …
**Toolchain Version:** …
**SDK Version:** …
> Sample pull request

- app/src/main/java/edu/uw/tcss450/chatapp/AuthActivity.java
> Practice for push and pull 

- app/src/main/java/edu/uw/tcss450/chatapp/AuthActivity.java
- app/src/main/java/edu/uw/tcss450/chatapp/MainActivity.java
> push test by Taehong

- .idea/.name
- app/src/main/java/edu/uw/tcss450/chatapp/MainActivity.java
- app/src/main/res/drawable/ic_chat_black_24dp.xml
- app/src/main/res/drawable/ic_contact_black_24dp.xml
- app/src/main/res/drawable/ic_home_black_24dp.xml
- app/src/main/res/drawable/ic_weather_black_24dp.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/menu/bottom_nav_menu.xml
- app/src/main/res/values/strings.xml
-Added vector assets
(home, contact, chat, weather)
-created bottom_nav_menu.xml
-Added menu to activity_main.xml
- There is minor issue with <button> in activity_main.xml, but didn't touch it because other member just created it.
- Ran the application in simulator and confirmed the menubar was correctly updated in activity_main.xml
> Create and update bottom_nave_menu bar

- app/build.gradle
- app/src/main/java/ui/HomeFragment.java
- app/src/main/java/ui/HomeViewModel.java
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/values/strings.xml
- Created basic homeFragment
- Put place some placeholders in homeFragment
- Add required strings in string.xml
- Created empty HomeViewModel.java 
- Ran the application in simulator
> Update for home Fragment and viewmodel

- app/build.gradle
- app/src/main/java/edu/uw/tcss450/chatapp/ui/HomeFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/HomeViewModel.java
- app/src/main/res/layout/fragment_home.xml
- build.gradle
Minor changes that included moving the UI folder into the proper package as well as add SafeArgs and Volley to list of dependencies. 
* Hardware:
* Toolchain:
* SDK:
> Move UI folder + add dependencies

- app/src/main/java/edu/uw/tcss450/chatapp/utils/PasswordValidator.java
Password validator that will be used later for Registration.
* Hardware:
* Toolchain:
* SDK:
> Password Validator Interface

- app/src/main/java/edu/uw/tcss450/chatapp/ui/auth/register/RegisterFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/auth/signin/SignInFragment.java
- app/src/main/res/layout/fragment_register.xml
- app/src/main/res/layout/fragment_sign_in.xml
This pull has two commits, creating registration fragment and Sign in Fragment. Nothing has touched yet, but I will be fixing these as we go forward with sprint 1
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [x ] Any dependent changes have been merged and published in downstream modules
> Registartion

- app/src/main/java/edu/uw/tcss450/chatapp/ui/weather/WeatheListFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/weather/WeatherFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/weather/WeatherListRecyclerViewAdapter.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/weather/WeatherListViewModel.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/weather/WeatherPost.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/weather/WeatherPostFragment.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_weathe_list.xml
- app/src/main/res/layout/fragment_weather.xml
- app/src/main/res/layout/fragment_weather_post.xml
- app/src/main/res/menu/bottom_nav_menu.xml
* Hardware:
* Toolchain:
* SDK:
> added empty fragments and classes for the weather front-end

- app/build.gradle
- app/src/main/java/edu/uw/tcss450/chatapp/MainActivity.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/chat/ChatFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/chat/ChatViewModel.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/contact/ContactFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/contact/ContactViewModel.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/home/HomeFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/home/HomeViewModel.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/fragment_chat.xml
- app/src/main/res/layout/fragment_contact.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/menu/bottom_nav_menu.xml
- app/src/main/res/navigation/auth_graph.xml
- app/src/main/res/navigation/main_graph.xml
- Update for bottom menubar navigation
- Update navigation package
- Created empty required fragments
- Moved Home fragments into ui.home package
- Fixed wrong fragments connection in menu bar
* Hardware:
* Toolchain:
* SDK:
- [] I have commented my code, particularly in hard-to-understand areas
> Update for buttom menubar navigation and create empty fragments

- app/src/main/AndroidManifest.xml
- app/src/main/res/layout/fragment_sign_in.xml
- app/src/main/res/navigation/auth_graph.xml
- Updated for displaying the sign-in page at the beginning of the app
- Fixed typo in signin fragment .xml
- Fixed typo and displaying order
* Hardware:
* Toolchain:
* SDK:
> Updated signin page as a starting points and fixed typo

- app/src/main/AndroidManifest.xml
- app/src/main/java/edu/uw/tcss450/chatapp/ui/auth/register/RegisterViewModel.java
- app/src/main/java/edu/uw/tcss450/chatapp/ui/auth/signin/SignInViewModel.java
Added internet accessibilities and endpoint updates to the registration and sign-in.
> Seungku kim work

- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/values/strings.xml
- Added detail mock-up design in home fragment
- Added strings for place holder
- None
* Hardware:
* Toolchain:
* SDK:
> Added detail mock-up design in home fragment

- app/src/main/AndroidManifest.xml
This change addresses the need by giving the permissions to send
requests over the internet.
* Hardware:
* Toolchain:
* SDK:
> Add permissions for making requests over the internet.

- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/home/HomeFragment.java
- app/src/main/res/drawable/cursor_color.xml
- app/src/main/res/layout/fragment_email_verification.xml
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_lost_password.xml
- app/src/main/res/layout/fragment_register.xml
- app/src/main/res/layout/fragment_sign_in.xml
cursor color change to white for some editTexts (signin fragment, register fragment, lost password, and email verification) because it wasn't showing up because of the theme we're using.
added the current weather, city, weather condition in the home page because the instructor was strongly suggesting to use that kind of looks for the home page. 
run on android studio
**Test …
> Looks and feels

- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/WeatherDailyRecyclerViewAdapter.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/WeatherData.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/WeatherHourlyRecyclerViewAdapter.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/WeatherListFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/WeatherListViewModel.java
some javadoc and comments for the weather classes
gets the weather data from the webservice and display them on the weather fragment. 
* Hardware:
* Toolchain:
* SDK:
> Added Javadoc and some comments for the weather classes

- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatListFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatListRecyclerViewAdapter.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatListViewModel.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatMessage.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatRecyclerViewAdapter.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatRoomFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatRoomViewModel.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatSendViewModel.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatViewModel.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/WeatherDailyRecyclerViewAdapter.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/WeatherData.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/WeatherHourlyRecyclerViewAdapter.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/WeatherListFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/WeatherListViewModel.java
* Hardware:
* Toolchain:
* SDK:
> branch update

- app/src/main/java/edu/uw/tcss450/chatapp_group1/MainActivity.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatListFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/chat/ChatRecyclerViewAdapter.java
- app/src/main/res/layout/fragment_chat_list.xml
- app/src/main/res/layout/fragment_chat_room.xml
Fixes chat/messaging bugs and implemented the feedback Charles gave us during our Sprint 2 demo meeting. Various style/layout updates of chat fragments, update text coloring to be more visible and consistent with neighboring components. Fix push notification issue where user sending a message would receive a notification of their own sent message. Fix issue of keyboard soft-pushing chat room cards upwards, hindering view of edit text box.
Addresses all chat-related tasks.
Tested functionality on two different devices, creating new chat rooms, deleting chat rooms, sending messages between the devices, etc.
> Messaging bug fixing

- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/auth/register/EmailVerificationFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/auth/register/EmailVerificationViewModel.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/auth/register/RegisterFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/auth/signin/SignInFragment.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/auth/signin/SignInViewModel.java
- app/src/main/res/navigation/auth_graph.xml
These changes are for making sure that the user is verified when they try to sign in. The client code will use the server endopoints to check if the user has verified or not. When the user verifies their email then an endpoint will be hit that updates the table so that the user is now verified. That will only happen if the email verification code they entered in was correct.
> Email verification

- app/src/main/java/edu/uw/tcss450/chatapp_group1/MainActivity.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/ui/weather/LocationFragment.java
- app/src/main/res/layout/fragment_location.xml
- app/src/main/res/layout/fragment_weather_list.xml
UI is updated components added and positions fixed
map marker is fixed
run on android studio
* Hardware:
* Toolchain:
* SDK:
> Weather sprint 3

- app/src/main/java/edu/uw/tcss450/chatapp_group1/MainActivity.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/model/NewAcceptCountViewModel.java
- app/src/main/java/edu/uw/tcss450/chatapp_group1/services/PushReceiver.java
- This is for implementing live contact list which was mentioned from sprint3 meeting
- Used push notification to update list when they get updates list
- Added push receiver for accepting friend list
- Created new view model to count accept pushy notification
- Created pushy notification for accepting
- No Fixing 
- Tested through andoird studio, postman, and visual studio
> Contact updates for covering sprint3 feedbacks
